services:
    _defaults:
        autowire: true

    dimetrodon.hideonlineblock.listener:
        class: dimetrodon\hideonlineblock\event\main_listener
        tags:
            - { name: event.listener }
